config/routes.rb
Rails.application.routes.draw do
  resources :contests
  resources :students
  resources :teams
  resources :schools
  root to: 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contest.rb
class Contest < ApplicationRecord
  has_many :results
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:name, :date, :number_of_problems, :img_url)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_with(model: contest, local: true) do |form| %>
  <% if contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contest_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.text_field :date, id: :contest_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :number_of_problems %>
    <%= form.number_field :number_of_problems, id: :contest_number_of_problems, class: 'form-control' %>
  </div>


  <div>
    <%= form.filestack_field :img_url, 'Upload Your Contest Pdf or Picture!',  pickerOptions: {'fromSources': ["local_file_system","url","imagesearch","facebook","instagram","googledrive","dropbox","evernote"]}, accept:[".pdf","image/*","text/plain",".doc",".docx",".docm"], id: 'school_picture_addition' %>


  </div>

<br><br>
  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing Contest</h1>

<%= render 'form', contest: @contest %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contests</h1>

<table class = 'table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Number of problems</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= link_to contest.name, contest %></td>
        <td><%= contest.date %></td>
        <td><%= contest.number_of_problems %></td>
        <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
        <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New Contest</h1>

<%= render 'form', contest: @contest %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contest.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @contest.date %>
</p>

<p>
  <strong>Number of problems:</strong>
  <%= @contest.number_of_problems %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @contest.img_url %>
</p>

<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>